### PR TITLE
Add irb/completion

### PR DESCRIPTION
**Pull request by pingram3030**
There is tab completion built in to irb, but only if you include this line. If you would like to have tab completion of all the things, merge away :)

### CODE REVIEW

**Comment by creideiki** [comment]
Looks good, thanks. However, we really, really prefer GnuPG-signed commits. Would it be possible for you to sign and re-push? [Here](https://help.github.com/articles/about-gpg/) is GitHub's documentation on how to set it up.

**Comment by pingram3030** [comment]
I think I sorted out the GPG thing, thanks for the inclusion :)

**Comment by creideiki** [comment]
Hmm. Something is not quite right here. Git claims that your commit looks like this:
```
commit 1dbf340726116aa572d569e534f6ba55c1e46ac9
gpg: Signature made Wed 25 Jan 2017 01:07:36 PM CET using RSA key ID D738C4F4
gpg: requesting key D738C4F4 from hkp server keys.gnupg.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: Can't check signature: No public key
```
With a key that doesn't exist on the keyservers. But GnuPG finds another key for your e-mail address:
```
$ gpg --search-keys pingram.au
gpg: searching for "pingram.au" from hkp server keys.gnupg.net
(1)     Phil Ingram (pingram3030) <pingram.au@REDACTED>
          4096 bit RSA key C0F8AAD5, created: 2016-01-12, expires: 2026-01-09
Keys 1-1 of 1 for "pingram.au".  Enter number(s), N)ext, or Q)uit > q
```

**Comment by pingram3030** [comment]
lol, I forgot to upload my pub key :D. fixed..

**Comment by pingram3030** [comment]
lol, I forgot to upload my pub key :D. I just sent it to keys.gnupg.net, but at the time of writing this it's not showing up in the CLI, but is through the webui. That last key no longer exists because it was on a laptop owned by my former employer.

**Pull request merged**
