### PR TITLE
Example warehouse

### PR DESCRIPTION
**Pull request by creideiki**
An example warehouse with pseudonymous data for illustrative purposes, with lots and lots of text explaining what is there and why.

### CODE REVIEW

**Comment by notCalle** [comment]
IP related objects should ether manage both IPv4 and IPv6 addresses, or be renamed to indicate their IPv4-onlyness.

**Comment by notCalle** [comment]
Chassis objects are not very DRY, with basically the same information already present in the name being repeated in `identity.yaml`. I would suggest something along the lines of:

`chassis/<vendor>:<dash-separated-model>:<serial>`

``` yaml
- chassis.vendor:
  - synthesize_regexp:
      sources: &pallet_chassis
        chassis:
          key: "pallet.chassis"
          regexp: "^(?<vendor>[^:]*):((?<line>[^:-]*)-)?((?<series>[^:-]*)-)?(?<model>[^:]*):(?<serial>[^:]*)$"
      produce: "#[vendor]"
- chassis.model:
  - synthesize_regexp:
      sources: *pallet_chassis
      produce:
        - "#[line] #[series] #[model]"
        - "#[line] #[model]"
        - "#[model]"
- chassis.serial:
  - synthesize_regexp:
      sources: *pallet_chassis
      produce: "#[serial]"
```

The DRY source regexp YAML reference magic requires #9 to work.

**Comment by creideiki** [comment]
Both valid points in the grand scheme of things, but out of scope for this pull request, which is about documenting the current state. Changes to the current state are better addressed in separate pull requests which change the code and the example warehouse simultaneously.

**Comment by notCalle** [comment]
Fair enough, #12 #13.

**Pull request merged**
